version: 2

models:
  - name: int_dados_pilotos
    description: "Tabela intermediária que consolida as estatísticas gerais da carreira de cada piloto.
      O modelo agrega pontos obtidos em corridas e sprints, além de computar métricas de desempenho
      como vitórias, pódios, pole positions e posições de largada. Cada linha representa um piloto,
      contendo o resumo de sua performance em todas as corridas registradas no dataset. No código nós
      fazemos um group by utilizando o id_piloto, agrupando as informações por piloto. Para somarmos tanto
      os pontos utilizados em corrida sprint quanto em corridas principais utilizamos a função SUM, com coalesce
      para evitar que fique como NULL. Também é utilizada algumas vezes a função COUNT, para contarmos os valores
      baseado no que está dentro do filtro determinado em filter."
    columns:
      - name: id_piloto
        description: "Identificador único do piloto."
      - name: pontos_totais_carreira
        description: "Soma total dos pontos conquistados pelo piloto em toda a carreira."
      - name: vitorias
        description: "Número total de vitórias do piloto."
      - name: podios
        description: "Número total de pódios do piloto."
      - name: pole_positions
        description: "Quantidade de pole positions do piloto."
      - name: largadas_top10
        description: "Número de vezes que o piloto largou dentro do top 10."
      - name: largadas_fora_top10
        description: "Quantidade de vezes que o piloto largou fora do top 10."


  - name: int_titulos_pilotos
    description: "Este modelo calcula a quantidade total de títulos de cada piloto da Fórmula 1 ao longo de suas carreiras.
      Ele aplica corretamente as regras históricas de pontuação vigentes em cada período, incluindo o sistema
      antigo utilizado antes de 1990, que considerava apenas os 11 melhores resultados de cada piloto na temporada.
      O objetivo principal da tabela é identificar, para cada ano, qual piloto foi campeão ao somar os pontos
      válidos daquele período, e posteriormente contar quantas vezes cada piloto aparece como campeão ao longo
      de todas as temporadas registradas.

      Lógica geral do modelo
      O cálculo é dividido em três etapas principais:
      1. Pontuação por corrida
      Cada linha representa uma corrida de um piloto, somando pontos de corrida e pontos de sprint quando existirem.
      Também é atribuído um ranking das corridas por piloto em cada ano (1 = maior pontuação no ano), o que permite
      aplicar corretamente a regra de descarte do sistema antigo.
      2. Pontuação válida por ano
      - Para anos anteriores ou iguais a 1990, apenas as 11 melhores corridas do piloto contam para o campeonato.
        Esse era o sistema oficial da Fórmula 1 na época: mesmo que o piloto participasse de mais corridas, apenas
        seus melhores resultados eram considerados.
      - Para anos após 1990, todos os resultados passam a contar, pois a FIA encerrou o critério de descarte.
      A tabela agrega a soma de pontos válidos por piloto e ano, respeitando essas diferenças entre os sistemas.
      3. Identificação dos campeões e contagem de títulos
      Para cada ano, o modelo precisa identificar qual piloto obteve a maior pontuação válida. A partir dessa identificação,
      é possível determinar o campeão de cada temporada e, posteriormente, contar quantas vezes cada piloto foi campeão.
      Para isso, é utilizado um SELECT DISTINCT ON (ano_corrida) ordenado por pontos_no_ano decrescente. Esse comando retorna
      exatamente uma linha por ano, garantindo que o piloto com maior pontuação seja escolhido como campeão.
      O uso do subselect é necessário porque o PostgreSQL não permite agrupar diretamente após um DISTINCT ON.  
      Em outras palavras, o `DISTINCT ON` é aplicado antes da agregação, e o agrupamento externo (`GROUP BY id_piloto`) só pode
      acontecer após o subconjunto de campeões por ano já estar definido.
      Se tentássemos agrupar sem o subselect, o banco retornaria erro de sintaxe ou ambiguidades, porque DISTINCT ON escolhe uma linha por ano,
      GROUP BY precisa ser aplicado sobre um conjunto já filtrado e não é possível contar títulos enquanto ainda existem múltiplas linhas por ano.
      O subselect isola corretamente o resultado desejado (um campeão por ano), permitindo então que o `GROUP BY id_piloto`
      conte quantas vezes cada piloto vence.
      Assim, o subselect é fundamental para separar essas duas etapas: Selecionar o campeão de cada ano e agrupar por piloto e contar títulos

      A tabela final contém uma linha por piloto, com o total de títulos (campeonatos) que esse piloto ganhou,
      aplicando fielmente o sistema de pontuação vigente em cada época da Fórmula 1."
    columns:
      - name: id_piloto
        description: "Identificador único do piloto."
      - name: titulos
        description: "Quantidade de títulos."

  - name: int_titulos_equipes
    description: "Nessa tabela é apenas setado o número de títulos já conquistados por cada equipe, na história da F1."
    columns:
      - name: id_equipe
        description: "Identificador único da equipe"
      - name: titulos
        description: "Número de títulos da equipe"


  - name: int_status
    description: "Nessa tabela é retornado em formato json todos os status que um piloto teve em um ano. Os status são retornados dessa forma para ser fácil de analisa-los como 
     um todo, podendo ter uma boa visão geral da temporada e um dos possíveis motivos de um piloto ter performado melhor que outro."
    columns:
      - name: id_piloto
        description: "Identificador único do piloto"
      - name: ano
        description: "Ano em que foram agrupados os dados"

  - name: int_posicao_campeonato
    description: "A tabela apresenta a classificação final de cada piloto em todas as temporadas, aplicando corretamente as regras históricas de pontuação da Fórmula 1. O objetivo
     é refletir a posição oficial de cada piloto em cada campeonato, considerando os diferentes sistemas de descarte de resultados utilizados entre as décadas de 1950 e 1990. Na 
     primeira CTE, é calculada a pontuação individual de cada corrida, somando os pontos obtidos nas corridas tradicionais com os pontos conquistados em corridas sprint. Em seguida, 
     aplica-se um ROW_NUMBER() particionado por piloto e ano, ordenando as corridas da maior para a menor pontuação. Esse passo é fundamental para permitir a aplicação do sistema de
     descartes adotado pela Fórmula 1 antes de 1991, quando apenas os melhores resultados do piloto eram considerados para a pontuação final da temporada. Na segunda CTE, são somadas 
     apenas as pontuações válidas de cada piloto em cada ano. Para temporadas até 1990, apenas os 11 melhores resultados são considerados; esse comportamento é implementado filtrando 
     apenas as linhas onde rn <= 11. A partir de 1991, todos os resultados passam a valer, eliminando a necessidade de qualquer filtro adicional. O resultado dessa etapa é a pontuação 
     final do piloto na temporada, já compatível com o regulamento vigente da época. Por fim, na consulta principal, é atribuída a colocação de cada piloto no campeonato. Isso é feito 
     por meio de outro ROW_NUMBER(), agora particionado por ano e ordenado pela pontuação anual em ordem decrescente. O valor resultante representa a posição final do piloto no 
     campeonato daquele ano, com 1 indicando o campeão e os demais números representando as posições subsequentes."
    columns:
      - name: id_piloto
        description: "Identificador único do piloto"
      - name: ano
        description: "Ano da temporada"
      - name: pontos_no_ano
        description: "Quantidade de pontos marcados pelo piloto na temporada"
      - name: colocacao_no_campeonato
        description: "Posição que o piloto terminou o campeonato"

  - name: int_pit_stops
    description: "Nessa tabela é retornada a quantidade de pit stops feitos por um piloto durante uma temporada, ajudando a fazer análises sobre sua temporada. Para fazer essa conta 
     é feito um cálculo utilizando COUNT, agrupando pelo id_piloto e ano, dessa forma tendo a quantidade exatas de paradas em um ano por piloto."
    columns:
      - name: id_piloto
        description: "Identificador único do piloto"
      - name: ano
        description: "Ano em que foram agrupados os dados"
      - name: numero_paradas
        description: "Número de paradas do piloto na temporada"

  - name: int_pilotos_equipe
    description: "Nessa tabela é retornado o nome de todos os pilotos que já passaram por uma equipe em formato json. Podemos identificar qual a equipe pelo id_equipe. Para criar a 
     estrutura é utilizada as funções JSONB_BUILD_OBJECT que é utilizada para criar objetos JSON diretamente a partir de pares chave-valor informados na chamada da função. Após 
     isso é utilizada a função JSONB_AGG que pega todas as linhas do valor informado e transforma em um array JSONB. E por último é utilizada a função JSONB_BUILD_OBJECT que 
     cria um objeto JSONB a partir de pares chave-valor. Dessa forma conseguimos retornar em estrutura JSON todos os pilotos que já pilotaram pela equipe em alguma corrida."
    columns:
      - name: id_piloto
        description: "Identificador único do piloto"
      - name: ano
        description: "Ano em que foram agrupados os dados"
      - name: numero_paradas
        description: "Número de paradas do piloto na temporada"

  - name: int_dados_equipes
    description: "Tabela intermediária que consolida as estatísticas gerais de desempenho de cada equipe ao longo de todas as corridas registradas. O modelo soma os pontos 
     obtidos tanto em corridas principais quanto em corridas sprint e calcula diversas métricas de performance, incluindo vitórias, pódios, pole positions e padrões de largada. 
     Cada linha representa uma equipe, trazendo um resumo completo de seu histórico competitivo na tabela. No código, realizamos um GROUP BY utilizando o campo id_equipe, 
     garantindo que todas as informações sejam consolidadas por equipe. Para calcular a pontuação total, utilizamos a função SUM, somando os pontos da corrida principal e da 
     sprint, com COALESCE para evitar valores nulos. Além disso, são utilizadas múltiplas expressões COUNT(*) FILTER (...) para contabilizar ocorrências específicas, como 
     vitórias, pódios, poles e largadas dentro ou fora do top 10, sempre de acordo com as condições definidas em cada cláusula FILTER."
    columns:
      - name: id_equipe
        description: "Identificador único da equipe"
      - name: vitorias
        description: "Número total de vitórias da equipe."
      - name: podios
        description: "Número total de pódios da equipe."
      - name: pole_positions
        description: "Quantidade de pole positions da equipe."
      - name: largadas_top10
        description: "Número de vezes que a equipe largou dentro do top 10."
      - name: largadas_fora_top10
        description: "Quantidade de vezes que a equipe largou fora do top 10."

  - name: int_dados_corrida
    description: "Tabela intermediária que consolida o resultado final de cada corrida, trazendo de forma estruturada os pilotos que compuseram o pódio e o piloto que largou
     na pole position. Cada linha representa uma única corrida, identificada por id_corrida, permitindo consultar rapidamente os principais destaques daquele evento. A 
     construção do modelo é dividida em duas etapas: a CTE pole_position identifica, para cada corrida, qual piloto largou na pole position, filtrando as linhas onde 
     posicao_largada = 1 e obtendo o nome correspondente por meio de um MAX(nome_piloto) para garantir um único valor por corrida. Em seguida, a CTE podio monta o pódio 
     utilizando expressões condicionais (CASE WHEN) que extraem o nome do piloto conforme sua posição final (1º, 2º ou 3º), novamente aplicando MAX para consolidar uma linha por 
     corrida. A consulta final realiza um LEFT JOIN entre as duas CTEs, unificando o pódio e a pole position em uma única estrutura por corrida."
    columns:
      - name: id_corrida
        description: "Identificador único do piloto"
      - name: primeiro_colocado
        description: "Ano em que foram agrupados os dados"
      - name: segundo_colocado
        description: "Número de paradas do piloto na temporada"
      - name: terceiro_colocado
        description: "Número de paradas do piloto na temporada"
      - name: pole_position
        description: "Número de paradas do piloto na temporada"
